### ISSUE TITLE
[Bug]: 启动时报错

### ISSUE THREAD

**Issue by xiao-k233** [walinejs/waline#1722]
### 问题描述 | Describe the bug

我之前在使用时，使用github注册会：{"errno":500,"errmsg":"Not initialized"}，这个情况是在docker
独立部署时会：
```node_modules/jsdom/lib/jsdom/browser/parser/html.js:170
    after._pushedOnStackOfOpenElements?.();
                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/xiaok/node_modules/jsdom/lib/jsdom/browser/parser/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)```

### 问题网站 | Website URL

服务器部署在自家公网ip就不提供了哈

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/issues?q=is%3Aissue+Not+initialized+is%3Aclosed

**Comment by xiao-k233** [comment]
> https://github.com/walinejs/waline/issues?q=is%3Aissue+Not+initialized+is%3Aclosed

我用docker时，按照文档使用-e参数加了变量

**Comment by lizheming** [comment]
自己检查下 docker 命令吧，出现问题就是配置没对

**Comment by xiao-k233** [comment]
> 自己检查下 docker 命令吧，出现问题就是配置没对

```
sudo docker run -d   -e LEAN_ID=uYcxxJt****AWOdr2cbuv123131XbMMI   -e LEAN_KEY=K***HUkUFN123131ydkgS25geJ7   -p 8360:8360   lizheming/waline
```

这样没问题吧，直接复制的官网文档
