### ISSUE TITLE
[Bug]: Docker 私有部署 Waline 无法连接 Docker MySql

### ISSUE THREAD

**Issue by vhkj** [walinejs/waline#1825]
### 问题描述 | Describe the bug

`部署方式`: Docker 部署
`部署命令`:

```shell
docker run -d \
  --name waline \
  --restart=unless-stopped \
  --link mysql:mysql \
  -e MYSQL_HOST=mysql \
  -e MYSQL_DB=waline \
  -e MYSQL_USER=root \
  -e MYSQL_PASSWORD="ef4FGH5665" \
  -p 8360:8360 \
  lizheming/waline
```

`注`: 按 Waline 文档说明手动导入了 `waline.sql`, 导入到了数据库 `waline` 中. 另外, 我部署的 `nextcloud` 也是连接这个 docker mysql, 在正常工作.

`docker logs waline`:

```
[2023-02-26T03:55:06.122] [14] [DEBUG] - Post Comment Start!
[2023-02-26T03:55:06.123] [14] [DEBUG] - Post Comment initial Data: {
  link: 'blog.lasolo.cn',
  mail: 'desheng@lasolo.cn',
  nick: '得胜',
  pid: undefined,
  rid: undefined,
  ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
  url: '/',
  comment: '可能有点慢送上',
  ip: '127.0.0.1',
  insertedAt: '2023-02-25T19:55:06.123Z',
  user_id: undefined
}
Error: connect ENOENT tcp://172.17.0.13:3306
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
    --------------------
    at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/app/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/app/node_modules/mysql/lib/Pool.js:48:16)
    at /app/node_modules/think-helper/index.js:83:10
    at new Promise (<anonymous>)
    at /app/node_modules/think-helper/index.js:82:12
    at ThinkMysql.getConnection (/app/node_modules/think-mysql/index.js:89:69)
    at /app/node_modules/think-mysql/index.js:229:21
    at /app/node_modules/think-debounce/index.js:19:16 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: 'tcp://172.17.0.13:3306',
  fatal: true
}
[2023-02-26T03:55:06.123] [14] [DEBUG] - Comment IP 127.0.0.1 check OK!
```

### 提交评论后出现错误弹窗

```connect ENOENT tcp://172.17.0.13:3306```

### 关于 MySql 日志

它最近的日志是前几天的, 今天没有.

### 关于 docker 部署时使用 LeanCloud 国际版存储来部署

这个是没问题的, 可以正常工作, 但我想用本地的数据库, 这些数据都存在我本机上

### 问题网站 | Website URL

https://comments.lasolo.cn

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
看起来应该还是 MySQL 连接的问题，check 下 MySQL 的链接配置是否正确，从报错信息来看应该是找不到 MySQL

**Comment by vhkj** [comment]
> 看起来应该还是 MySQL 连接的问题，check 下 MySQL 的链接配置是否正确，从报错信息来看应该是找不到 MySQL

## 现在算是不完美的解决了, 启动 docker 容器的参数如下:

```
docker run -it -d \
  --name waline \
  --restart=unless-stopped \
  -e MYSQL_HOST=mysql \
  -e MYSQL_DB=waline \
  -e MYSQL_USER=waline \
  -e MYSQL_PASSWORD=waline \
  -p 8360:8360 \
  lizheming/waline
```

去掉了 `--link mysql:mysql`, 应该是容器内的某模块不支持 `MYSQL_HOST=mysql` 这种形式, 只支持 IP 或 DOMAIN(maybe), 可惜了, 这个 IP 在 mysql 容器重启时时可能变化的。

**除了授权用户 `waline` 对数据库 `waline` 的所有操作权限外, 另一个针对 mysql 8.0 兼容旧数据库版本的验证方式的步骤是:**

```
ALTER USER 'waline'@'172.17.0.%' IDENTIFIED WITH mysql_native_password BY 'your password';
```

**相当于使用旧版本的密码哈希方式以便兼容**,  不操作这个会报错 `ER_NOT_SUPPORTED_AUTH_MODE`.
