### ISSUE TITLE
[Bug]: 请求 pageview 返回错误

### ISSUE THREAD

**Issue by WingsZeng** [walinejs/waline#2091]
### 问题描述 | Describe the bug

后端版本 v1.31.4, 请求 pageview 时返回错误 `{"errno":500,"errmsg":"key[updatedAt] is reserved"}`

vercel 后端 log 如下:

```
[33m[2023-09-19T07:19:40.700] [8] [WARN][39m - [Deprecated] /article API will be deprecated in the next major version, please don't use it anymore. If you are using `@waline/client` please upgrade to `@waline/client@3`. For other scenarios, you can use `/api/article` to replace it.
Error: key[updatedAt] is reserved
    at checkReservedKey (/var/task/node_modules/leancloud-storage/dist/node/object.js:52:11)
    at /var/task/node_modules/leancloud-storage/dist/node/object.js:789:11
    at Function.mapObject (/var/task/node_modules/underscore/underscore-node-f.cjs:761:27)
    at child.set (/var/task/node_modules/leancloud-storage/dist/node/object.js:788:19)
    at /var/task/node_modules/@waline/vercel/src/service/storage/leancloud.js:409:16
    at Array.map (<anonymous>)
    at module.exports.update (/var/task/node_modules/@waline/vercel/src/service/storage/leancloud.js:405:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at module.exports.postAction (/var/task/node_modules/@waline/vercel/src/controller/article.js:80:17)
    at cors (/var/task/node_modules/@koa/cors/index.js:108:16)
```

使用 /api/article 也不行. 后端已尝试重新部署.

```sh
❯ curl -X POST https://blog-comments-waline-ipxpmdz7e-wingszeng.vercel.app/article -H "Content-Type: application/json" -d '{"path": "/test/", "type": "time", "action":"inc"}'    
{"errno":500,"errmsg":"key[updatedAt] is reserved"}%

❯ curl -X POST https://blog-comments-waline-ipxpmdz7e-wingszeng.vercel.app/api/article -H "Content-Type: application/json" -d '{"path": "/test/", "type": "time", "action":"inc"}'
{"errno":500,"errmsg":"key[updatedAt] is reserved"}%

❯ curl -X POST https://blog-comments-waline-3bt28hfhb-wingszeng.vercel.app/article -H "Content-Type: application/json" -d '{"path": "/test/", "type": "time", "action":"inc"}'
184%
```

前两条后端是 v1.31.4 的, 最后一条是之前部署的 v1.11.0 版本, 能正常请求.

### 问题网站 | Website URL

https://blog-comments-waline-ipxpmdz7e-wingszeng.vercel.app

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
可以先回滚到 1.31.3 的版本，应该是最新的版本引入的问题

**Comment by wbsu2003** [comment]
外面列表上的阅读次数正常，但是进入文章后阅读次数显示 [object object]，回退到 1.31.3 就正常了

**Comment by lizheming** [comment]
@wbsu2003 嗯嗯，我周末处理下

**Comment by lizheming** [comment]
这个问题 `@waline/vercel@1.31.7` 最新版已修复，有问题的同学请升级到最新版即可解决。
