### ISSUE TITLE
[Bug]:  {"errno":500,"errmsg":"update data is empty, original data is {"like":1}"}

### ISSUE THREAD

**Issue by jalen-qian** [walinejs/waline#2123]
### My operator on page is:
<img width="577" alt="image" src="https://github.com/walinejs/waline/assets/12954176/7973fee2-e531-44a5-a09e-c83219b81965">

### http request
```shell
curl 'https://waline.jalen-qian.com/comment/1?lang=zh-cn' \
  -X 'PUT' \
  -H 'authority: waline.jalen-qian.com' \
  -H 'accept: */*' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'authorization: Bearer undefined' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: https://jalen-qian.com' \
  -H 'pragma: no-cache' \
  -H 'referer: https://jalen-qian.com/' \
  -H 'sec-ch-ua: "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' \
  --data-raw '{"like":true}' \
  --compressed
```
### The http response is :
{"errno":500,"errmsg":"update data is empty, original data is {\"like\":1}"}

I also looked the logs on my server(Docker), here is the logs:
```shell
[2023-10-16T00:24:31.820] [13] [INFO] - SQL: SELECT * FROM `wl_Comment` WHERE ( `id` = '1' ), Time: 3ms
Error: update data is empty, original data is {"like":1}
    at /app/node_modules/think-model/lib/model.js:574:31
    at Generator.next (<anonymous>)
    at step (/app/node_modules/think-model/lib/model.js:1:129)
    at /app/node_modules/think-model/lib/model.js:1:299
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### 问题网站 | Website URL

www.jalen-qian.com

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/blob/main/assets/waline.sql#L27 如果是升级过来的用户的话，需要单独给数据表新增 `like` 字段，具体见更新日志 https://t.me/walinelog/42

**Comment by jalen-qian** [comment]
Thank you very much! After upgrading the latest SQL statement and rebuilding the image, the issue has been resolved!
