### ISSUE TITLE
[Feature]: 是否考虑将 dist/component.js 改成 esm 格式 || [Feature]: Whether to consider changing dist/component.js to esm format

### ISSUE THREAD

**Issue by alomerry** [walinejs/waline#2332]
### 功能概述 | Describe the feature

按照 [此示例](https://waline.js.org/cookbook/import/project.html#%E5%9C%A8-vue-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E5%AF%BC%E5%85%A5) 构建失败，可以考虑将 dist/component.js 改成 esm 格式吗

```shell
Error [ERR_REQUIRE_ESM]: require() of ES Module /root/workspace/mix/blog/node_modules/.pnpm/@waline+client@3.0.0-alpha.11_typescript@5.3.3/node_modules/@waline/client/dist/component.js from /root/workspace/mix/blog/.vite-ssg-temp/nvk3vmsnqt/main.cjs not supported.
Instead change the require of component.js in /root/workspace/mix/blog/.vite-ssg-temp/nvk3vmsnqt/main.cjs to a dynamic import() which is available in all CommonJS modules.
    at Module.<anonymous> (/root/workspace/mix/blog/.vite-ssg-temp/nvk3vmsnqt/main.cjs:5:19)
    at build (file:///root/workspace/mix/blog/node_modules/.pnpm/vite-ssg@0.23.6_vite@5.1.1_vue-router@4.2.5_vue@3.4.18/node_modules/vite-ssg/dist/node.mjs:999:115)
    at async Object.handler (file:///root/workspace/mix/blog/node_modules/.pnpm/vite-ssg@0.23.6_vite@5.1.1_vue-router@4.2.5_vue@3.4.18/node_modules/vite-ssg/dist/node/cli.mjs:34:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

<details>

<summary>package.json</summary>

```json
{
  "type": "module",
  "private": true,
  "packageManager": "pnpm@8.15.1",
  "scripts": {
    "build": "cross-env NODE_ENV=production vite-ssg build && esno ./scripts/rss.ts",
    "dev": "vite --port 3333 --open",
    "preview": "vite preview",
    "lint": "eslint ."
  },
  "dependencies": {
    "@vueuse/core": "^10.7.2",
    "dayjs": "^1.11.10",
    "floating-vue": "2.0.0-beta.24",
    "nprogress": "^0.2.0",
    "shiki": "1.0.0-rc.0",
    "vue": "^3.4.15",
    "vue-router": "4.2.5",
    "vue-router-better-scroller": "^0.0.0"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^2.6.4",
    "@iconify/json": "^2.2.180",
    "@octokit/rest": "^20.0.2",
    "@shikijs/markdown-it": "^1.0.0-rc.0",
    "@shikijs/transformers": "^1.1.2",
    "@shikijs/twoslash": "^1.0.0-rc.0",
    "@types/diacritics": "^1.3.3",
    "@types/fs-extra": "^11.0.4",
    "@types/markdown-it": "^13.0.7",
    "@types/markdown-it-container": "^2.0.9",
    "@types/markdown-it-emoji": "^2.0.4",
    "@types/markdown-it-link-attributes": "^3.0.4",
    "@types/nprogress": "^0.2.3",
    "@types/prompts": "^2.4.9",
    "@unhead/vue": "^1.8.10",
    "@unocss/reset": "^0.58.5",
    "@vitejs/plugin-vue": "^5.0.3",
    "@waline/client": "3.0.0-alpha.11",
    "cross-env": "^7.0.3",
    "diacritics": "^1.3.0",
    "eslint": "8.52.0",
    "eslint-plugin-format": "^0.1.0",
    "esno": "^4.0.0",
    "fast-glob": "^3.3.2",
    "feed": "^4.2.2",
    "fs-extra": "^11.2.0",
    "gray-matter": "^4.0.3",
    "lint-staged": "^15.2.2",
    "markdown-it": "^14.0.0",
    "markdown-it-anchor": "^8.6.7",
    "markdown-it-container": "^4.0.0",
    "markdown-it-emoji": "^3.0.0",
    "markdown-it-github-alerts": "^0.3.0",
    "markdown-it-link-attributes": "^4.0.1",
    "markdown-it-table-of-contents": "^0.6.0",
    "nanoid": "^5.0.5",
    "picocolors": "^1.0.0",
    "pnpm": "^8.15.1",
    "prompts": "^2.4.2",
    "shiki": "^1.0.0-rc.0",
    "simple-git": "^3.22.0",
    "simple-git-hooks": "^2.9.0",
    "typescript": "^5.3.3",
    "unocss": "^0.58.5",
    "unplugin-auto-import": "^0.17.5",
    "unplugin-icons": "^0.18.5",
    "unplugin-vue-components": "^0.26.0",
    "unplugin-vue-markdown": "^0.26.0",
    "vite": "^5.0.12",
    "vite-plugin-inspect": "^0.8.3",
    "vite-plugin-pages": "^0.32.0",
    "vite-ssg": "^0.23.6",
    "vite-svg-loader": "^5.1.0"
  },
  "simple-git-hooks": {
    "pre-commit": "pnpm lint-staged"
  },
  "lint-staged": {
    "*": "eslint --fix"
  }
}
```

</details>

---
### Feature Overview | Describe the feature

Follow [this example](https://waline.js.org/cookbook/import/project.html#%E5%9C%A8-vue-%E9%A1%B9%E7%9B%AE%E4%B8% AD%E5%AF%BC%E5%85%A5) The build failed. Can you consider changing dist/component.js to esm format?

```shell
Error [ERR_REQUIRE_ESM]: require() of ES Module /root/workspace/mix/blog/node_modules/.pnpm/@waline+client@3.0.0-alpha.11_typescript@5.3.3/node_modules/@waline/client/dist /component.js from /root/workspace/mix/blog/.vite-ssg-temp/nvk3vmsnqt/main.cjs not supported.
Instead change the require of component.js in /root/workspace/mix/blog/.vite-ssg-temp/nvk3vmsnqt/main.cjs to a dynamic import() which is available in all CommonJS modules.
    at Module.<anonymous> (/root/workspace/mix/blog/.vite-ssg-temp/nvk3vmsnqt/main.cjs:5:19)
    at build (file:///root/workspace/mix/blog/node_modules/.pnpm/vite-ssg@0.23.6_vite@5.1.1_vue-router@4.2.5_vue@3.4.18/node_modules/vite-ssg/dist /node.mjs:999:115)
    at async Object.handler (file:///root/workspace/mix/blog/node_modules/.pnpm/vite-ssg@0.23.6_vite@5.1.1_vue-router@4.2.5_vue@3.4.18/node_modules/vite- ssg/dist/node/cli.mjs:34:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

<details>

<summary>package.json</summary>

```json
{
  "type": "module",
  "private": true,
  "packageManager": "pnpm@8.15.1",
  "scripts": {
    "build": "cross-env NODE_ENV=production vite-ssg build && esno ./scripts/rss.ts",
    "dev": "vite --port 3333 --open",
    "preview": "vite preview",
    "lint": "eslint ."
  },
  "dependencies": {
    "@vueuse/core": "^10.7.2",
    "dayjs": "^1.11.10",
    "floating-vue": "2.0.0-beta.24",
    "nprogress": "^0.2.0",
    "shiki": "1.0.0-rc.0",
    "vue": "^3.4.15",
    "vue-router": "4.2.5",
    "vue-router-better-scroller": "^0.0.0"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^2.6.4",
    "@iconify/json": "^2.2.180",
    "@octokit/rest": "^20.0.2",
    "@shikijs/markdown-it": "^1.0.0-rc.0",
    "@shikijs/transformers": "^1.1.2",
    "@shikijs/twoslash": "^1.0.0-rc.0",
    "@types/diacritics": "^1.3.3",
    "@types/fs-extra": "^11.0.4",
    "@types/markdown-it": "^13.0.7",
    "@types/markdown-it-container": "^2.0.9",
    "@types/markdown-it-emoji": "^2.0.4",
    "@types/markdown-it-link-attributes": "^3.0.4",
    "@types/nprogress": "^0.2.3",
    "@types/prompts": "^2.4.9",
    "@unhead/vue": "^1.8.10",
    "@unocss/reset": "^0.58.5",
    "@vitejs/plugin-vue": "^5.0.3",
    "@waline/client": "3.0.0-alpha.11",
    "cross-env": "^7.0.3",
    "diacritics": "^1.3.0",
    "eslint": "8.52.0",
    "eslint-plugin-format": "^0.1.0",
    "esno": "^4.0.0",
    "fast-glob": "^3.3.2",
    "feed": "^4.2.2",
    "fs-extra": "^11.2.0",
    "gray-matter": "^4.0.3",
    "lint-staged": "^15.2.2",
    "markdown-it": "^14.0.0",
    "markdown-it-anchor": "^8.6.7",
    "markdown-it-container": "^4.0.0",
    "markdown-it-emoji": "^3.0.0",
    "markdown-it-github-alerts": "^0.3.0",
    "markdown-it-link-attributes": "^4.0.1",
    "markdown-it-table-of-contents": "^0.6.0",
    "nanoid": "^5.0.5",
    "picocolors": "^1.0.0",
    "pnpm": "^8.15.1",
    "prompts": "^2.4.2",
    "shiki": "^1.0.0-rc.0",
    "simple-git": "^3.22.0",
    "simple-git-hooks": "^2.9.0",
    "typescript": "^5.3.3",
    "unocss": "^0.58.5",
    "unplugin-auto-import": "^0.17.5",
    "unplugin-icons": "^0.18.5",
    "unplugin-vue-components": "^0.26.0",
    "unplugin-vue-markdown": "^0.26.0",
    "vite": "^5.0.12",
    "vite-plugin-inspect": "^0.8.3",
    "vite-plugin-pages": "^0.32.0",
    "vite-ssg": "^0.23.6",
    "vite-svg-loader": "^5.1.0"
  },
  "simple-git-hooks": {
    "pre-commit": "pnpm lint-staged"
  },
  "lint-staged": {
    "*": "eslint --fix"
  }
}
```

</details>

**Comment by lizheming** [comment]
https://stackblitz.com/edit/vitejs-vite-4sv87o?file=src%2FApp.vue 可以用最新版试试，我测试是可以按照 ESM 模式正常工作的。

**Comment by alomerry** [comment]
> https://stackblitz.com/edit/vitejs-vite-4sv87o?file=src%2FApp.vue 可以用最新版试试，我测试是可以按照 ESM 模式正常工作的。
> 
> https://stackblitz.com/edit/vitejs-vite-4sv87o?file=src%2FApp.vue You can try it with the latest version. I tested that it can work normally in ESM mode.

好的，我尝试一下~

**Comment by Mister-Hope** [comment]
你那个错误是你在require esm。有ssg渲染的话要把整个项目改成esm的模式，或者配一下vite的ssr渲染
