### ISSUE TITLE
[Bug]: MongoDB 改变了 Request URL 格式

### ISSUE THREAD

**Issue by leimao** [walinejs/waline#2404]
### 问题描述 | Describe the bug

MongoDB URL 的新要求：
```
mongodb://admin:<password>@ac-1cwx7lh-shard-00-00.ktanrgk.mongodb.net:27017,ac-1cwx7lh-shard-00-01.ktanrgk.mongodb.net:27017,ac-1cwx7lh-shard-00-02.ktanrgk.mongodb.net:27017/?ssl=true&replicaSet=atlas-maqbvt-shard-0&authSource=admin&retryWrites=true&w=majority&appName=Waline-DB
```

Waline URL 的内容：
```
mongodb://admin:<password>@ac-1cwx7lh-shard-00-00.ktanrgk.mongodb.net:27017,ac-1cwx7lh-shard-00-01.ktanrgk.mongodb.net:27017,ac-1cwx7lh-shard-00-02.ktanrgk.mongodb.net:27017/Waline-DB?replicaSet=atlas-maqbvt-shard-0&authSource=admin&ssl=true
```

注意新要求里的 `appName`.

错误信息：
```
(node:8) [DEP0170] DeprecationWarning: The URL mongodb://admin:<password>@ac-1cwx7lh-shard-00-00.ktanrgk.mongodb.net:27017,ac-1cwx7lh-shard-00-01.ktanrgk.mongodb.net:27017,ac-1cwx7lh-shard-00-02.ktanrgk.mongodb.net:27017/Waline-DB?replicaSet=atlas-maqbvt-shard-0&authSource=admin&ssl=true is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)
TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/var/task/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/var/task/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
```

### 问题网站 | Website URL

N/A

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MongoDB

**Comment by SSRVodka** [comment]
这两种 URL 格式目前都是没问题的，只不过在 cluster 中创建的数据库位置有所不同（留空默认 `test`）。appName 也不是必须的。
烦请你刷新一下评论区再查看一下日志，方便定位真正的问题
