### ISSUE TITLE
[Bug] [独立部署 直接运行] [SQLite数据库] :  未配置LeanCloud相关的环境变量时， 程序运行报错 || [Bug] [Independent deployment, direct operation] [SQLite database]: When the environment variables related to LeanCloud are not configured, the program will report an error when running.

### ISSUE THREAD

**Issue by pygyme** [walinejs/waline#2501]
### 问题描述 | Describe the bug

根据官方文档独立部署一节， 采用直接运行的方式部署服务， 其中使用了SQLite数据库。

通过查找Issue， 发现是跟 [Issue 10](https://github.com/walinejs/waline/issues/10) 一样的问题。

目前对LeanCloud相关环境变量设置了一个无效的值， 采用这种方式进行绕过， 设置之后程序可以正常运行。
```
export LEAN_ID=abcd
export LEAN_KEY=abcd
export LEAN_SERVER=abcd
```

开发者如果有空的话， 麻烦处理一下。

---
### Problem description | Describe the bug

According to the independent deployment section of the official documentation, the service is deployed by direct operation, using the SQLite database.

By searching for the Issue, I found that it is the same problem as [Issue 10](https://github.com/walinejs/waline/issues/10).

Currently, an invalid value is set for LeanCloud related environment variables. This method is used to bypass it. After setting, the program can run normally.
```
export LEAN_ID=abcd
export LEAN_KEY=abcd
export LEAN_SERVER=abcd
```

If the developer is free, please take care of it.

**Comment by lizheming** [comment]
可以提供下具体的配置和错误信息看一下，你引用的 issue 已经是 4 年前的问题了，很早就已经被修复了。如果还有类似的问题，可能需要具体再看一下。

另外如果你配置了 LEAN_KEY 之类的字段的话，应该是会优先使用 LeanCloud 存储服务的，不应该 SQLite 还能正常使用，所以理论上你应该是没有配置生效的。https://github.com/walinejs/waline/blob/main/packages/server/src/config/config.js#L55-L80

**Comment by pygyme** [comment]
1. 安装项目， 系统是 Ubuntu 22.04
```shell
root@ubunut22:~/waline# apt-get install nodejs npm sqlite3
root@ubunut22:~/waline# npm config set registry=https://registry.npmjs.org

root@ubunut22:~/waline# mkdir -p /root/waline && cd /root/waline
root@ubunut22:~/waline# wget https://github.com/walinejs/waline/blob/main/assets/waline.sqlite
root@ubunut22:~/waline# npm install @waline/vercel --save
added 568 packages, and audited 569 packages in 1m

39 packages are looking for funding
  run `npm fund` for details

35 vulnerabilities (32 moderate, 3 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
root@ubunut22:~/waline# npm list
waline@ /root/waline
└── @waline/vercel@1.31.13

root@ubunut22:~/waline#
```

2. 卧槽， 35个漏洞，这不得根据提示处理一下？
```
root@ubunut22:~/waline# npm audit fix
root@ubunut22:~/waline# npm audit fix --force
root@ubunut22:~/waline# npm list
waline@ /root/waline
└── @waline/vercel@0.7.2

root@ubunut22:~/waline#
```
处理完成，发现版本降级到了 0.7.2， 根据提示，还是有漏洞，这他喵的修了跟没修一个样。 所以这些前端库的提示到底是干啥的？

2. 运行项目
```
root@ubunut22:~/waline# npm list
waline@ /root/waline
└── @waline/vercel@0.7.2

root@ubunut22:~/waline# node node_modules/@waline/vercel/vanilla.js
[2024-05-13T16:29:01.275] [1358] [INFO] - Server running at http://127.0.0.1:8360
[2024-05-13T16:29:01.282] [1358] [INFO] - ThinkJS version: 3.2.15
[2024-05-13T16:29:01.282] [1358] [INFO] - Environment: production
[2024-05-13T16:29:01.282] [1358] [INFO] - Workers: 1
TypeError: appId must be a string
    at Object.init (/root/waline/node_modules/leancloud-storage/dist/node/init.js:100:21)
    at Object.<anonymous> (/root/waline/node_modules/@waline/vercel/src/service/storage/leancloud.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at exports.interopRequire (/root/waline/node_modules/think-loader/loader/util.js:17:13)
    at /root/waline/node_modules/think-loader/loader/common.js:16:26
^C
root@ubunut22:~/waline# node node_modules/@waline/vercel/vanilla.js
[2024-05-13T16:29:27.383] [1372] [INFO] - Server running at http://127.0.0.1:8360
[2024-05-13T16:29:27.396] [1372] [INFO] - ThinkJS version: 3.2.15
[2024-05-13T16:29:27.396] [1372] [INFO] - Environment: production
[2024-05-13T16:29:27.396] [1372] [INFO] - Workers: 1
TypeError: appId must be a string
    at Object.init (/root/waline/node_modules/leancloud-storage/dist/node/init.js:100:21)
    at Object.<anonymous> (/root/waline/node_modules/@waline/vercel/src/service/storage/leancloud.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at exports.interopRequire (/root/waline/node_modules/think-loader/loader/util.js:17:13)
    at /root/waline/node_modules/think-loader/loader/common.js:16:26
^C
root@ubunut22:~/waline#
```

**Comment by lizheming** [comment]
1. 如果是用的 0.7.2 那确实可能会有之前的问题，这个版本是3年前的版本了，确实有点古早
2. 漏洞处理比较复杂，涉及各种依赖，之前我看过一下，大部分还好，可以先不处理
3. 报错是因为新版本需要 node >= 16 才可以哈，https://github.com/walinejs/waline/blob/main/packages/server/package.json#L56-L58 你在安装依赖的时候应该有提示信息的。node 12 已经是前年开始不维护的版本了，如果比较关心安全方面的话，建议升级。
4. 如果觉得折腾环境比较麻烦的话，建议直接使用 Docker 部署，会更方便点。
