### ISSUE TITLE
[Bug]: 邮箱通知收不到邮件啊 || [Bug]: Email notification cannot be received.

### ISSUE THREAD

**Issue by Tasselmi** [walinejs/waline#2703]
### 问题描述 | Describe the bug

如题，作者使用的邮箱（被通知邮箱）是gmail的邮箱。

邮箱服务我先是配的Ethereal邮箱服务，日志如下：
```log
[2024-09-03T17:07:15.716] [14] [DEBUG] - Comment have been added to storage.
Notification mail send success: {
  accepted: [Array],
  rejected: [],
  ehlo: [Array],
  envelopeTime: 758,
  messageTime: 562,
  messageSize: 1170,
  response: '250 Accepted [STATUS=new MSGID=ZaFyK0TysrzrYMcMZtbRx7EfOOXR3VB3AAAAFeZWd1mWrB4uv7snM2ixb1A]',
  envelope: [Object],
  messageId: '<9c01626e-0ba4-cba0-c47c-f3c6d7f70edf@ethereal.email>'
}
[2024-09-03T17:07:19.333] [14] [DEBUG] - Comment notify done!
[2024-09-03T17:07:19.333] [14] [DEBUG] - Comment post hooks postSave done!
```
如果我没看错，这个应该是说发送成功了，但是我去我的gmail邮箱check发现是没有收到任何邮件的。

于是，我把邮箱服务换成163的，结果，直接报错了。
```log
[2024-09-03T18:43:35.731] [13] [DEBUG] - Comment have been added to storage.
Mail send fail: Error: Invalid login: 535 Error: authentication failed
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:798:19)
    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1577:34)
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:554:26)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:982:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:763:14)
    at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'EAUTH',
  response: '535 Error: authentication failed',
  responseCode: 535,
  command: 'AUTH PLAIN'
}
[2024-09-03T18:43:36.065] [13] [DEBUG] - Comment notify done!
```

比较确定账密是没有问题的，因为我还特地到网页登录了一遍确认了下。

### 问题网站 | Website URL

https://scalapie.com/2024/08/31/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2%E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF%E4%B9%8B7/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

---
### Problem description | Describe the bug

As the title states, the email address used by the author (the email address being notified) is a gmail email address.

For the email service, I first configured the Ethereal email service. The logs are as follows:
```log
[2024-09-03T17:07:15.716] [14] [DEBUG] - Comment have been added to storage.
Notification mail send success: {
  accepted: [Array],
  rejected: [],
  ehlo: [Array],
  envelopeTime: 758,
  messageTime: 562,
  messageSize: 1170,
  response: '250 Accepted [STATUS=new MSGID=ZaFyK0TysrzrYMcMZtbRx7EfOOXR3VB3AAAAFeZWd1mWrB4uv7snM2ixb1A]',
  envelope: [Object],
  messageId: '<9c01626e-0ba4-cba0-c47c-f3c6d7f70edf@ethereal.email>'
}
[2024-09-03T17:07:19.333] [14] [DEBUG] - Comment notify done!
[2024-09-03T17:07:19.333] [14] [DEBUG] - Comment post hooks postSave done!
```
If I read it correctly, this should mean that it was sent successfully, but I checked my gmail email and found that I did not receive any email.

So, I changed the email service to 163, and as a result, an error was reported directly.
```log
[2024-09-03T18:43:35.731] [13] [DEBUG] - Comment have been added to storage.
Mail send fail: Error: Invalid login: 535 Error: authentication failed
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:798:19)
    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1577:34)
    at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:554:26)
    at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:982:20)
    at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:763:14)
    at TLSSocket.SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'EAUTH',
  response: '535 Error: authentication failed',
  responseCode: 535,
  command: 'AUTH PLAIN'
}
[2024-09-03T18:43:36.065] [13] [DEBUG] - Comment notify done!
```

I am relatively sure that there is no problem with the account password, because I also specially logged in to the website to confirm.

### Question Website | Website URL

https://scalapie.com/2024/08/31/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2 %E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF%E4%B9%8B7/

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
1. 发送成功是指邮件发送过去了，但发送过去了并不代表用户就能看到。邮件的发送过程会有非常多原因导致用户看不到，可能会因为收件服务商的防火墙过滤，也可能会因为其它的规则导致无法收到。具体的原因我们没办法排查，如果需要研究可以自己再多深入研究下。
2. 163 邮箱的话不能用登录的密码，密码是需要在设置里有一个专门的随机码。

**Comment by Tasselmi** [comment]
> 1. 发送成功是指邮件发送过去了，但发送过去了并不代表用户就能看到。邮件的发送过程会有非常多原因导致用户看不到，可能会因为收件服务商的防火墙过滤，也可能会因为其它的规则导致无法收到。具体的原因我们没办法排查，如果需要研究可以自己再多深入研究下。
> 2. 163 邮箱的话不能用登录的密码，密码是需要在设置里有一个专门的随机码。
> 
> 1. Successful sending means that the email has been sent, but sending it does not mean that the user can see it. There are many reasons why the user cannot see the email during the sending process. It may be due to the firewall filtering of the receiving service provider, or it may not be received due to other rules. We can't investigate the specific reasons. If you need to research, you can do more in-depth research yourself.
> 2. For 163 mailboxes, you cannot use the login password. The password requires a special random code in the settings.

第一个Ethereal，我去试了下，以前用的Ethereal现在好像拉稀了，尝试给gmail和其他邮箱发邮件都收不到，但是在Ethereal的记录能看到发送记录，但是其他的好几个邮箱都是收不到，初步确认是Ethereal拉稀出问题了应该。

第二个163，我去瞧一瞧，之前是真不知道还有这样的。

**Comment by Tasselmi** [comment]
163的搞定啦，感恩。

```log
[2024-09-03T20:26:11.940] [14] [DEBUG] - Comment have been added to storage.
Notification mail send success: {
  accepted: [Array],
  rejected: [],
  ehlo: [Array],
  envelopeTime: 117,
  messageTime: 1307,
  messageSize: 1144,
  response: '250 Mail OK queued as gzsmtp2,sSgvCgB3zytkANdmf3nKAg--.622S2 1725366373',
  envelope: [Object],
  messageId: '<52c29e58-f068-5938-493d-41c8740047ef@163.com>'
}
[2024-09-03T20:26:13.774] [14] [DEBUG] - Comment notify done!
[2024-09-03T20:26:13.774] [14] [DEBUG] - Comment post hooks postSave done!
```

**Comment by lizheming** [comment]
Waline 暂时还没有支持邮件快捷回复的功能，有需要的话欢迎 PR，这个 issue 就先关闭了。
