### ISSUE TITLE
[Bug]: 升级 @waline/vercel 至 1.32.1 后出现 500 INTERNAL_SERVER_ERROR 问题 || [Bug]: 500 INTERNAL_SERVER_ERROR problem occurred after upgrading @waline/vercel to 1.32.1

### ISSUE THREAD

**Issue by Candinya** [walinejs/waline#2719]
### 问题描述 | Describe the bug

升级 `@waline/vercel` 从 `1.32.0` 至 `1.32.1` 后， Vercel 页面访问时出现 500 错误，提示函数运行崩溃。部分时候可以打开主页，但无法拉取评论（正常的情况可以参考 https://waline.candinya.com/ ，已经 rollback 到 1.32.0 ，环境变量都没有改动）。尝试访问后台 `/ui` 时跳转至登录界面，但输入账号密码提示错误。

Vercel 后台有收集到以下日志（已对敏感信息做隐藏处理）：

```log
[32m[2024-09-17T13:44:21.806] [13] [INFO][39m - mongodb://***:***@***-00-00.***.mongodb.net:27017,***-00-01.***.mongodb.net:27017,***-00-02.***.mongodb.net:27017/***?replicaSet=atlas-***-shard-0&authSource=admin&ssl=true
Uncaught Exception: ReferenceError: DOMException is not defined
    at Dt (/opt/rust/nodejs.js:8:13122)
    at ClientRequest.<anonymous> (/opt/rust/nodejs.js:8:11324)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketCloseListener (node:_http_client:467:11)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:301:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Node.js process exited with exit status: 129. The logs above can help with debugging the issue.
```

由于 1.32.1 已经发布有一段时间，且未找到其他相关 issue ，不排除是这边环境的边缘特例，我也会尝试帮忙确认更多的信息。非常感谢您的帮助。

### 问题网站 | Website URL

https://waline-candiblog-r6wy8iq6w-nya-candys-projects.vercel.app/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MongoDB

---
### Problem description | Describe the bug

After upgrading `@waline/vercel` from `1.32.0` to `1.32.1`, a 500 error occurred when accessing the Vercel page, prompting that the function crashed. Sometimes the homepage can be opened, but comments cannot be pulled (for normal conditions, please refer to https://waline.candinya.com/, which has been rolled back to 1.32.0 and the environment variables have not been changed). When trying to access the backend `/ui`, it jumps to the login interface, but the error prompt when entering the account password is incorrect.

Vercel has collected the following logs in the background (sensitive information has been hidden):

```log
[32m[2024-09-17T13:44:21.806] [13] [INFO] [39m - mongodb://***:***@***-00-00.***.mongodb. net:27017,***-00-01.***.mongodb.net:27017,***-00-02.***.mongodb.net:27017/***?replicaSet=atlas-** *-shard-0&authSource=admin&ssl=true
Uncaught Exception: ReferenceError: DOMException is not defined
    at Dt (/opt/rust/nodejs.js:8:13122)
    at ClientRequest.<anonymous> (/opt/rust/nodejs.js:8:11324)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketCloseListener (node:_http_client:467:11)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at TCP.<anonymous> (node:net:301:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Node.js process exited with exit status: 129. The logs above can help with debugging the issue.
```

Since 1.32.1 has been released for a while, and no other related issues have been found, it cannot be ruled out that it is a marginal exception in this environment. I will also try to help confirm more information. Thank you very much for your help.

### Question Website | Website URL

https://waline-candiblog-r6wy8iq6w-nya-candys-projects.vercel.app/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

MongoDB

**Comment by lizheming** [comment]
看一下 Vercel 后台设置的 Node 版本，如果是 16.x 建议升级到 20.x 重新部署下再试试。

**Comment by Candinya** [comment]
确实是这个问题，更新至 20.x 后重新构建就一切正常了，非常感谢！
