### ISSUE TITLE
[Bug]: 收到新评论或回复别人没有邮件通知 || [Bug]: No email notification when receiving new comments or replying to others

### ISSUE THREAD

**Issue by yeminxi** [walinejs/waline#2829]
### 问题描述 | Describe the bug

不管谁给我发评论我都收不到通知。给别人回复，别人也没有邮件通知。用的是QQ邮箱，也设置有作者邮箱。也试过重新部署过。
![image](https://github.com/user-attachments/assets/351792ca-f305-445d-9ac2-aeac12f31c08)

### 问题网站 | Website URL

https://ymxblog.us.kg/message/ ， https://wl.ymxapi.us.kg

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

I don't get notifications from anyone who comments. When I reply to others, there is no email notification from others. I use QQ mailbox, and I also have the author’s mailbox set up. Also tried redeploying.
![image](https://github.com/user-attachments/assets/351792ca-f305-445d-9ac2-aeac12f31c08)

### Question Website | Website URL

https://ymxblog.us.kg/message/ , https://wl.ymxapi.us.kg

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by yeminxi** [comment]
Mail send fail: Error: Mail command failed: 501 Mail from address must be same as authorization user.
    at SMTPConnection._formatError (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:807:19)
    at SMTPConnection._actionMAIL (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:1616:34)
    at SMTPConnection.<anonymous> (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:1085:18)
    at SMTPConnection._processResponse (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:991:20)
    at SMTPConnection._onData (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:772:14)
    at TLSSocket.SMTPConnection._onSocketData (/var/task/node_modules/nodemailer/lib/smtp-connection/index.js:195:44)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {
  code: 'EENVELOPE',
  response: '501 Mail from address must be same as authorization user.',
  responseCode: 501,
  command: 'MAIL FROM'
}

**Comment by yeminxi** [comment]
已解决，QQ邮箱不能使用自定义邮箱发送。
