### ISSUE TITLE
Waline Server 运行抛出异常

### ISSUE THREAD

**Issue by rqh656418510** [walinejs/waline#608]
**问题描述 | Describe the bug**

Waline Server 基于最新的代码运行抛出如下异常，导致评论系统无法正常使用。

```
Error: Cannot find module 'deta'
Require stack:
- /app/node_modules/@waline/vercel/src/service/storage/deta.js
- /app/node_modules/think-loader/loader/util.js
- /app/node_modules/think-loader/loader/config.js
- /app/node_modules/think-loader/index.js
- /app/node_modules/thinkjs/lib/loader.js
- /app/node_modules/thinkjs/lib/application.js
- /app/node_modules/@waline/vercel/vanilla.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/node_modules/@waline/vercel/src/service/storage/deta.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] Deta
  - [ ] CloudBase
  - [x] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [x] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Mister-Hope** [comment]
Seems the same as #606
