### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by SaboZhang** [walinejs/waline#812]
### 功能概述 | Describe the feature

在centos上使用docker 部署一直提示connect ETIMEDOUT，使用的公网IP，并且数据库可以正常访问，在Windows的docker下同样的运行运行命令可以正常运行，nginx根据文档进行了配置。
访问地址：https://mes.luckyits.com
运行命令：
docker run -d --name waline -p 8360:8360 -v /mydocker/waline/data:/app/data -e TZ="Asia/Shanghai" -e MYSQL_HOST="服务器外网IP" -e MYSQL_DB="数据库" -e MYSQL_USER="用户名" -e MYSQL_PASSWORD="密码" -e AUTHOR_EMAIL="邮箱" -e SITE_NAME="网站名称" -e SENDER_NAME="博客留言" -e SITE_URL="https://www.luckyits.com" -e SMTP_SERVICE="QQ" -e SMTP_USER="QQ邮箱" -e SMTP_PASS="密码" -e 	SECURE_DOMAINS="域名" -e DISABLE_USERAGENT="true" -e AVATAR_PROXY="https://avatar.75cdn.workers.dev" -e IPQPS="30" --restart always lizheming/waline:latest

Error: connect ETIMEDOUT
2022-02-08T18:05:07.088605465Z     at PoolConnection.Connection._handleConnectTimeout (/app/node_modules/mysql/lib/Connection.js:409:13)
2022-02-08T18:05:07.088610532Z     at Object.onceWrapper (node:events:509:28)
2022-02-08T18:05:07.088613716Z     at Socket.emit (node:events:390:28)
2022-02-08T18:05:07.088616516Z     at Socket.emit (node:domain:475:12)
2022-02-08T18:05:07.088619155Z     at Socket._onTimeout (node:net:501:8)
2022-02-08T18:05:07.088621787Z     at listOnTimeout (node:internal/timers:557:17)
2022-02-08T18:05:07.088624597Z     at processTimers (node:internal/timers:500:7)
2022-02-08T18:05:07.088627224Z     --------------------
2022-02-08T18:05:07.088629827Z     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2022-02-08T18:05:07.088632519Z     at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
2022-02-08T18:05:07.088635248Z     at PoolConnection.connect (/app/node_modules/mysql/lib/Connection.js:116:18)
2022-02-08T18:05:07.088637852Z     at Pool.getConnection (/app/node_modules/mysql/lib/Pool.js:48:16)
2022-02-08T18:05:07.088640817Z     at Pool.releaseConnection (/app/node_modules/mysql/lib/Pool.js:157:10)
2022-02-08T18:05:07.088643439Z     at Pool._removeConnection (/app/node_modules/mysql/lib/Pool.js:277:8)
2022-02-08T18:05:07.088646031Z     at Pool._purgeConnection (/app/node_modules/mysql/lib/Pool.js:258:8)
2022-02-08T18:05:07.088658998Z     at Handshake.onConnect (/app/node_modules/mysql/lib/Pool.js:57:14)
2022-02-08T18:05:07.088662066Z     at Handshake.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
2022-02-08T18:05:07.088665380Z     at Handshake._callback (/app/node_modules/mysql/lib/Connection.js:488:16) {
2022-02-08T18:05:07.088668300Z   errorno: 'ETIMEDOUT',
2022-02-08T18:05:07.088670974Z   code: 'ETIMEDOUT',
2022-02-08T18:05:07.088673655Z   syscall: 'connect',
2022-02-08T18:05:07.088676446Z   fatal: true

**Comment by lizheming** [comment]
用 telnet 看下端口是否可访问吧，这应该就是你的数据库的网络连接问题

```
telnet <ip> <port>
```

**Comment by SaboZhang** [comment]
我在别的电脑上用navicat可以正常链接啊，对了我数据库是8.0但是加密方式已经改为低版本的加密方式了，在本地使用服务器上的mysql也可正常运行

**Comment by lizheming** [comment]
在你的服务器上 telnet 下提供下结果

**Comment by SaboZhang** [comment]
麻烦大佬了，是docker的问题 IPV4的网络转发被禁用了，修改的转发配置没有生效
