### ISSUE TITLE
[Bug]: 私有化容器部署并且使用postgres作为后端DB后的column "insertedAt" does not exist问题

### ISSUE THREAD

**Issue by kevin1sMe** [walinejs/waline#884]
### 问题描述 | Describe the bug

第一次正常部署好像没问题，但我把备份的pgsql的数据库重新导入到新的DB时（恢复DB），请求会返回这种内容：
```log
[2022-03-31T23:00:17.874] [15] [INFO] - SQL: SELECT "status","comment","insertedAt","link","mail","nick","pid","rid","ua","user_id","sticky","id" FROM "wl_comment" WHERE ( "url" = E'/post/[[我的页面]]/' ) AND ( "status" NOT IN (E'waiting',E'spam') ) ORDER BY insertedAt DESC, Time: 57ms
error: column "insertedAt" does not exist
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 178,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: 'Perhaps you meant to reference the column "wl_comment.insertedat".',
  position: '27',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3599',
  routine: 'errorMissingColumn'
```
了解到pgsql本身对于字段名称是如果不主动加双引号，会被DB转变为小写，然后这种情况下再次导入恢复DB后db的结构是小写的字段。

于是再次提供服务时，有了上述查询语句出错的情况。是否字段名不用驼峰而全换为小写加_呢，像mysql等命名规范也是这样的。
`因为考虑到数据库移植问题，不同的数据库大小写敏感不一致，如果以后移植容易出现问题`

那么当前，我应该怎么做？

### 问题网站 | Website URL

https://gameapp.club

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
关于这个问题，我查看了一下，大概的原因是由于之前底层的 pg 库没有增加引号包裹字段，所以会自动小写。Waline 是在上层做适配封装处理这个大小写的问题。

后续在将 Waline 的多数据库适配功能抽离成单独的组件 https://github.com/walinejs/dittorm 的过程中，对底层库进行了改造，使其支持了大写字段。Waline 在安装的时候使用了新版的底层 pg 库，倒是了上层和下层的不适配，从而导致了问题。

目前我已将底层 pg 库锁到老版本暂时解决这个问题。你可以升级到 `@waline/vercel@1.8.1` 的版本再测试一下。

关于字段驼峰，这个主要是历史包袱导致。Waline 早期在数据库和前端样式这块都是基于 Valine 改造而来，数据库字段一致能让 Valine 用户无缝迁移过来。而 Valine 的数据库是基于 LeanCloud 的 NoSQL 数据库，所以他们使用了驼峰的字段命名方式。后续 Walien 在增加 SQL 类的支持的时候才反应过来这个问题，但为时已晚，已经基于驼峰字段统一了每个数据库的字段了，再改就会非常麻烦了。

最后，鉴于该问题已由 #888 解决，所以你的 PR #886 我就关闭了。不过还是依旧非常感谢你的 PR~

**Comment by kevin1sMe** [comment]
好的，谢谢回复。确实，我在旧版本正常，最近出现此问题，你的解释已经很清晰，明白。同时建议，是否构建的镜像带上版本？

**Comment by kevin1sMe** [comment]
使用最新镜像还是没有解决此问题呢？需要我自行build Image吗？

**Comment by lizheming** [comment]
CI 更新似乎有点问题，我这边暂时手动更新了一下，可以再 check 一下
